<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-FSHBSE6" name="JustTest.UserTestDemo" tests="5" failures="0" timestamp="7 Jun 2022 08:50:56 GMT" time="0.463" errors="1">
  <testcase name="login_postmanchange" time="0.092" classname="JustTest.UserTestDemo"/>
  <testcase name="password" time="0.063" classname="JustTest.UserTestDemo"/>
  <testcase name="user_list_user" time="0.069" classname="JustTest.UserTestDemo"/>
  <testcase name="getAllLessUser" time="0.063" classname="JustTest.UserTestDemo">
    <error type="java.lang.AssertionError" message="expected [success] but found [未认证，请先登录]">
        <![CDATA[java.lang.AssertionError: expected [success] but found [未认证，请先登录]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:165)
	at JustTest.UserTestDemo.getAllLessUser(UserTestDemo.java:150)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at testngRun.main(testngRun.java:11)
]]>
    </error>
  </testcase> <!-- getAllLessUser -->
  <testcase name="login" time="0.176" classname="JustTest.UserTestDemo"/>
</testsuite> <!-- JustTest.UserTestDemo -->
